openapi: 3.0.3
info:
  title: HamrohUz - OpenAPI 1.0
  description: |-

    Some useful links:
    - [The Pet Store repository](https://github.com/HamrohUz)
    - [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: https://hamrohuz.swagger.io/api/v1
tags:
  - name: Hamroh
    description: service for travelling between cities
    externalDocs:
      description: Find out more
      url: http://swagger.io
  - name: authorization
    description: Access to Petstore orders
    externalDocs:
      description: Find out more about our store
      url: http://swagger.io
  - name: driver
    description: Operations about user
