#Database
POSTGRES_SQL_USERNAME: hamroh_admin
POSTGRES_SQL_PASSWORD: wts34a2@
POSTGRES_SQL_HOST: 127.0.0.1
POSTGRES_SQL_PORT: 5432
POSTGRES_SQL_DB: hamrohdata

#Server
SERVER_PORT: 9000
ACTIVE_PROFILE: dev

#Email Config
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: hamroh.go@gmail.com
EMAIL_PASSWORD: hriijyoxbyaeeoqb